// Generated by CoffeeScript 1.3.3
(function() {
  var exports;

  exports = window;

  exports.onOK = function() {
    var pb;
    pb = Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefService).getBranch('extensions.cperapera.');
    if (document.getElementById('ppk-dontshow').checked) {
      pb.setBoolPref('show_warning_dlg', false);
    }
    window["arguments"][0].out = {
      proceed: true
    };
    return true;
  };

}).call(this);
